# Generated by Django 4.2.13 on 2024-06-11 10:23

import django.core.validators
import event.validators

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('hotel_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('room_reservation_id', models.UUIDField()),
                ('timestamp', models.DateTimeField()),
                ('night_of_stay', models.DateField()),
                ('status', models.IntegerField(validators=[event.validators.validate_status])),
            ],
        ),
    ]
